feat(AutoComplete)
digitalservicebund/ris-ui pull request #31
Opened 2024-09-20 10:31 UTC by MasterCarl

This PR introduces a new AutoComplete component.
The PrimeVue AutoComplete component is wrapped to control how the options are being rendered, and to work around some issues with how the original component handles updates when working with objects instead of just strings for suggestions.

It builds on #26 for tooling and setup.

2024-09-30 17:09 UTC, andreasphil requested changes

2024-09-30 17:09 UTC, andreasphil commented on src/primevue/autocomplete/autocomplete.ts
> +import { base, small } from "../inputText/inputText";
Suggestion: here I would actually prefer to have some copy paste rather than creating a dependency between two different components.

2024-09-30 17:09 UTC, andreasphil commented on src/components/AutoComplete/AutoComplete.vue
> +        class="!absolute inset-y-0 right-12 my-auto mr-2"
Todo: here too, can we avoid `!important`?

2024-10-01 14:00 UTC, MasterCarl commented on package.json
> +    "@iconify-json/mdi": "^1.2.0",
I'll keep this for now, we can always streamline them later.

2024-10-01 14:02 UTC, merged